services:
  - type: cron
    name: romanya-bot
    schedule: "0 5 * * *"  # Her sabah 08:00 (Türkiye) için UTC 05:00
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
