services:
  - type: cron
    name: romanya-bot
    schedule: "0 5 * * *"  # UTC 05:00 = Türkiye saatiyle sabah 08:00
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
